/**
 * TypeScript mirrors of src-tauri/src/models/*.rs and operations/plan.rs.
 *
 * Hand-written for now rather than generated by ts-rs (see
 * docs/architecture.md §5.1's `A9`/ts-rs note) — that codegen pipeline is
 * future work; keep this file in sync with the Rust structs by hand until
 * then. `ByteSize` is a string on the wire (see models/size.rs) because
 * JavaScript's `number` loses precision above 2^53-1, which a large disk
 * genuinely exceeds.
 */

export type ByteSize = string;

export type BusType = "sata" | "nvme" | "usb" | "virtual" | "unknown";
export type MediaType = "hdd" | "ssd" | "unknown";
export type HealthStatus = "ok" | "warning" | "failing" | "unknown";
export type PartitionTable = "gpt" | "mbr" | "none";

export type FileSystem =
  | "ntfs"
  | "fat32"
  | "exFat"
  | "ext2"
  | "ext3"
  | "ext4"
  | "btrfs"
  | "xfs"
  | "linuxSwap"
  | "unformatted"
  | "unknown";

export type PartitionKind =
  | "efi"
  | "microsoftReserved"
  | "recovery"
  | "basicData"
  | "linuxFilesystem"
  | "linuxSwap"
  | "other";

/** Mirrors `models::partition::PartitionFlags` (a `bitflags` bitmask). */
export const PartitionFlags = {
  BOOT: 0b0000_0001,
  SYSTEM: 0b0000_0010,
  ACTIVE_MOUNT: 0b0000_0100,
  LOCKED: 0b0000_1000,
} as const;

export function hasFlag(flags: number, flag: number): boolean {
  return (flags & flag) !== 0;
}

export interface Partition {
  id: string;
  number: number;
  start: ByteSize;
  size: ByteSize;
  used: ByteSize | null;
  fs: FileSystem;
  kind: PartitionKind;
  label: string | null;
  flags: number;
  driveLetter: string | null;
  mountpoints: string[];
}

export type Segment =
  | { kind: "partition"; value: Partition }
  | { kind: "unallocated"; value: { start: ByteSize; size: ByteSize } };

export interface Disk {
  id: string;
  displayName: string;
  vendor: string;
  model: string;
  serial: string | null;
  bus: BusType;
  media: MediaType;
  size: ByteSize;
  logicalSectorSize: number;
  table: PartitionTable;
  health: HealthStatus;
  readOnly: boolean;
  isSystemDisk: boolean;
  layout: Segment[];
}

export type OperationRequest =
  | {
      type: "createPartition";
      disk: string;
      start: ByteSize;
      size: ByteSize;
      filesystem: FileSystem;
      label: string | null;
    }
  | { type: "deletePartition"; partition: string }
  | { type: "formatPartition"; partition: string; filesystem: FileSystem; label: string | null }
  | { type: "setLabel"; partition: string; label: string }
  | { type: "setDriveLetter"; partition: string; driveLetter: string };

export type RiskLevel = "low" | "medium" | "high" | "critical";

export function operationRisk(req: OperationRequest): RiskLevel {
  switch (req.type) {
    case "setLabel":
    case "setDriveLetter":
      return "low";
    case "createPartition":
      return "medium";
    case "deletePartition":
    case "formatPartition":
      return "critical";
  }
}

export interface AppInfo {
  version: string;
  /** "windows" or "linux" — drive letters (setDriveLetter) only exist on
   * Windows; Linux uses mountpoints instead. */
  platform: "windows" | "linux";
}
